server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/api/payment/getPaymentById/**         # 断言，路径相匹配的进行路由
            #- After=2021-04-13T18:16:44.902+08:00[Asia/Shanghai]  #设置时间之后有效
            #- Before=2021-04-13T18:16:44.902+08:00[Asia/Shanghai] #设置时间之前有效
            #- Between=2021-04-13T17:16:44.902+08:00[Asia/Shanghai],2021-04-13T18:16:44.902+08:00[Asia/Shanghai] #设置时间之间有效
            #- Cookie=username,lc #需要带cookie且用户名lc，利用cmd访问curl http://localhost:9527/api/payment/getPaymentById?id=11 --cookie "username=lc"
            #- Header=X-Request-Id, \d+ #请求头需要匹配正则传递正整数，利用cmd访问curl http://localhost:9527/api/payment/getPaymentById?id=11 -H "X-Request-Id:11"
            #- Host=**.lc.com #请求头需要带主机名称，利用cmd访问curl http://localhost:9527/api/payment/getPaymentById?id=11 -H "Host:lc.com"
            - Method=Get #get方式调用方法
            - Query=id, \d+ #带有id正整数的请求参数


        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/api/payment/getPaymentSp/**         # 断言，路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka



